<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'ptg',
  'description' => 'ptg_Products export',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'ptg_Products',
  'published_date' => '2020-06-02 10:29:59',
  'type' => 'module',
  'version' => 1591093799,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'ptg_Products',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/language/en_us.lang.php',
      'to_module' => 'AOS_Products',
      'language' => 'en_us',
    ),
  ),
  'custom_fields' => 
  array (
    'AOS_Productsptg_services_id_c' => 
    array (
      'id' => 'AOS_Productsptg_services_id_c',
      'name' => 'ptg_services_id_c',
      'label' => 'LBL_SERVICE_PTG_SERVICES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'AOS_Products',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 10:23:28',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'AOS_Productsservice_c' => 
    array (
      'id' => 'AOS_Productsservice_c',
      'name' => 'service_c',
      'label' => 'LBL_SERVICE',
      'comments' => 'Service',
      'help' => 'Service',
      'module' => 'AOS_Products',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 10:23:28',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'ptg_Services',
      'ext3' => 'ptg_services_id_c',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/detailviewdefs.php',
      'to' => 'custom/modules/AOS_Products/metadata/detailviewdefs.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/AOS_Products/metadata/detailviewdefs.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/editviewdefs.php',
      'to' => 'custom/modules/AOS_Products/metadata/editviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/AOS_Products/metadata/editviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/listviewdefs.php',
      'to' => 'custom/modules/AOS_Products/metadata/listviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Products\\Ext\\Vardefs\\_override_sugarfield_ptg_services_id_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Products\\Ext\\Vardefs\\_override_sugarfield_ptg_services_id_c.php',
    ),
    6 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Products\\Ext\\Vardefs\\_override_sugarfield_service_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Products\\Ext\\Vardefs\\_override_sugarfield_service_c.php',
    ),
  ),
);