<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'ptg',
  'description' => 'All fields and customizations for Voice Service Request module ',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'ptg_VoiceServiceRequest',
  'published_date' => '2020-06-02 12:24:07',
  'type' => 'module',
  'version' => 1591100647,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'ptg_VoiceServiceRequest',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.ptg_VoiceServiceRequest.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ptg_VoiceServiceRequest/language/en_us.lang.php',
      'to_module' => 'ptg_VoiceServiceRequest',
      'language' => 'en_us',
    ),
  ),
  'custom_fields' => 
  array (
    'ptg_VoiceServiceRequestaccount_id_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestaccount_id_c',
      'name' => 'account_id_c',
      'label' => 'LBL_CUSTOMER_NAME_ACCOUNT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 11:11:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestaos_products_id_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestaos_products_id_c',
      'name' => 'aos_products_id_c',
      'label' => 'LBL_SELECT_PRODUCT_AOS_PRODUCTS_ID',
      'comments' => '',
      'help' => '',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 11:25:13',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestbusiness_name_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestbusiness_name_c',
      'name' => 'business_name_c',
      'label' => 'LBL_BUSINESS_NAME',
      'comments' => 'Business Name',
      'help' => 'Business Name',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2020-06-02 11:13:20',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestchoose_the_suppliers_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestchoose_the_suppliers_c',
      'name' => 'choose_the_suppliers_c',
      'label' => 'LBL_CHOOSE_THE_SUPPLIERS',
      'comments' => 'Choose the Suppliers',
      'help' => 'Choose the Suppliers',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 11:50:22',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'choose_the_suppliers_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestcity_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestcity_c',
      'name' => 'city_c',
      'label' => 'LBL_CITY',
      'comments' => 'City',
      'help' => 'City',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2020-06-02 11:18:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestcomment_additional_info_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestcomment_additional_info_c',
      'name' => 'comment_additional_info_c',
      'label' => 'LBL_COMMENT_ADDITIONAL_INFO',
      'comments' => 'Comment & Additional Information',
      'help' => 'Comment & Additional Information',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 12:20:15',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '10',
      'ext3' => '300',
      'ext4' => NULL,
    ),
    'ptg_VoiceServiceRequestcountry_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestcountry_c',
      'name' => 'country_c',
      'label' => 'LBL_COUNTRY',
      'comments' => 'Country',
      'help' => 'Country',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2020-06-02 11:23:25',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestcustomer_name_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestcustomer_name_c',
      'name' => 'customer_name_c',
      'label' => 'LBL_CUSTOMER_NAME',
      'comments' => 'Customer Name',
      'help' => 'Customer Name',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 11:14:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => 'Accounts',
      'ext3' => 'account_id_c',
      'ext4' => NULL,
    ),
    'ptg_VoiceServiceRequestinternational_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestinternational_c',
      'name' => 'international_c',
      'label' => 'LBL_INTERNATIONAL',
      'comments' => 'International',
      'help' => 'International',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'radioenum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 11:40:29',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'international_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestlocal_phone_number_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestlocal_phone_number_c',
      'name' => 'local_phone_number_c',
      'label' => 'LBL_LOCAL_PHONE_NUMBER',
      'comments' => 'Local Phone Number',
      'help' => 'Local Phone Number',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'phone',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2020-06-02 11:15:45',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestmain_address_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestmain_address_c',
      'name' => 'main_address_c',
      'label' => 'LBL_MAIN_ADDRESS',
      'comments' => 'Main Address',
      'help' => 'Main Address',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2020-06-02 11:17:09',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestpostal_code_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestpostal_code_c',
      'name' => 'postal_code_c',
      'label' => 'LBL_POSTAL_CODE',
      'comments' => 'Postal Code',
      'help' => 'Postal Code',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2020-06-02 11:22:12',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestselect_product_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestselect_product_c',
      'name' => 'select_product_c',
      'label' => 'LBL_SELECT_PRODUCT',
      'comments' => 'Select Products',
      'help' => 'Select Products',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 11:25:13',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'AOS_Products',
      'ext3' => 'aos_products_id_c',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequeststate_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequeststate_c',
      'name' => 'state_c',
      'label' => 'LBL_STATE',
      'comments' => 'State',
      'help' => 'State',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 11:20:46',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'ptg_VoiceServiceRequestsuppliers_to_quote_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestsuppliers_to_quote_c',
      'name' => 'suppliers_to_quote_c',
      'label' => 'LBL_SUPPLIERS_TO_QUOTE',
      'comments' => 'Suppliers to Quote',
      'help' => 'Suppliers to Quote',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'multienum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 11:57:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'suppliers_to_quote_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'ptg_VoiceServiceRequestterms_to_quote_c' => 
    array (
      'id' => 'ptg_VoiceServiceRequestterms_to_quote_c',
      'name' => 'terms_to_quote_c',
      'label' => 'LBL_TERMS_TO_QUOTE',
      'comments' => 'Terms to Quote',
      'help' => 'Terms to Quote',
      'module' => 'ptg_VoiceServiceRequest',
      'type' => 'multienum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-06-02 11:36:22',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'terms_to_quote_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ptg_VoiceServiceRequest/metadata/SearchFields.php',
      'to' => 'custom/modules/ptg_VoiceServiceRequest/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ptg_VoiceServiceRequest/metadata/SearchFields.php',
      'to' => 'custom/working/modules/ptg_VoiceServiceRequest/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ptg_VoiceServiceRequest/metadata/detailviewdefs.php',
      'to' => 'custom/modules/ptg_VoiceServiceRequest/metadata/detailviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ptg_VoiceServiceRequest/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/ptg_VoiceServiceRequest/metadata/detailviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ptg_VoiceServiceRequest/metadata/editviewdefs.php',
      'to' => 'custom/modules/ptg_VoiceServiceRequest/metadata/editviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ptg_VoiceServiceRequest/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/ptg_VoiceServiceRequest/metadata/editviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ptg_VoiceServiceRequest/metadata/listviewdefs.php',
      'to' => 'custom/modules/ptg_VoiceServiceRequest/metadata/listviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ptg_VoiceServiceRequest/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/ptg_VoiceServiceRequest/metadata/quickcreatedefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ptg_VoiceServiceRequest/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/ptg_VoiceServiceRequest/metadata/quickcreatedefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_account_id_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_account_id_c.php',
    ),
    10 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_aos_products_id_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_aos_products_id_c.php',
    ),
    11 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_business_name_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_business_name_c.php',
    ),
    12 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_choose_the_suppliers_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_choose_the_suppliers_c.php',
    ),
    13 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_city_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_city_c.php',
    ),
    14 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_comment_additional_info_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_comment_additional_info_c.php',
    ),
    15 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_country_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_country_c.php',
    ),
    16 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_customer_name_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_customer_name_c.php',
    ),
    17 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_international_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_international_c.php',
    ),
    18 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_local_phone_number_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_local_phone_number_c.php',
    ),
    19 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_main_address_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_main_address_c.php',
    ),
    20 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_postal_code_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_postal_code_c.php',
    ),
    21 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_select_product_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_select_product_c.php',
    ),
    22 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_state_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_state_c.php',
    ),
    23 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_suppliers_to_quote_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_suppliers_to_quote_c.php',
    ),
    24 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_terms_to_quote_c.php',
      'to' => 'custom\\Extension\\modules\\ptg_VoiceServiceRequest\\Ext\\Vardefs\\_override_sugarfield_terms_to_quote_c.php',
    ),
  ),
);