<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'campaign_accounts' => 
  array (
    'id' => '5538668d-7b56-2a5f-3f47-5ee75a518559',
    'relationship_name' => 'campaign_accounts',
    'lhs_module' => 'Campaigns',
    'lhs_table' => 'campaigns',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'campaign_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_modified_user' => 
  array (
    'id' => '87115d8b-1f2a-55c6-148f-5ee75a671ce0',
    'relationship_name' => 'accounts_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_created_by' => 
  array (
    'id' => '8732a43a-03fe-4f41-429a-5ee75a732d26',
    'relationship_name' => 'accounts_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_assigned_user' => 
  array (
    'id' => '874f7bd5-780e-8f42-7e9a-5ee75a768e7e',
    'relationship_name' => 'accounts_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_accounts' => 
  array (
    'id' => '876be37f-11e8-da8e-ef5d-5ee75a442bd3',
    'relationship_name' => 'securitygroups_accounts',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'member_accounts' => 
  array (
    'id' => '87c10165-80b8-563b-f91d-5ee75a8a04d7',
    'relationship_name' => 'member_accounts',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_cases' => 
  array (
    'id' => '87db2d79-42e3-5332-c8d1-5ee75a327eaf',
    'relationship_name' => 'account_cases',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Cases',
    'rhs_table' => 'cases',
    'rhs_key' => 'account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_tasks' => 
  array (
    'id' => '87f5e35c-a352-e7ff-9850-5ee75ab2c8dc',
    'relationship_name' => 'account_tasks',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_notes' => 
  array (
    'id' => '8810393a-2c54-d321-3470-5ee75ae69f6d',
    'relationship_name' => 'account_notes',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_meetings' => 
  array (
    'id' => '882abe84-ce29-d167-03ac-5ee75ae88b3d',
    'relationship_name' => 'account_meetings',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_calls' => 
  array (
    'id' => '88451cb4-e351-81c4-4ee1-5ee75aaa933e',
    'relationship_name' => 'account_calls',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_emails' => 
  array (
    'id' => '885ebbe8-9af8-2c2c-8148-5ee75a877910',
    'relationship_name' => 'account_emails',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'emails',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => 'ForEmails',
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_leads' => 
  array (
    'id' => '88786d81-1741-9202-83e1-5ee75a9b0522',
    'relationship_name' => 'account_leads',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Leads',
    'rhs_table' => 'leads',
    'rhs_key' => 'account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_aos_quotes' => 
  array (
    'id' => '88aaf79e-8168-a8cd-8f30-5ee75a441afd',
    'relationship_name' => 'account_aos_quotes',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Quotes',
    'rhs_table' => 'aos_quotes',
    'rhs_key' => 'billing_account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_aos_invoices' => 
  array (
    'id' => '88c5ccfc-146e-7fda-43fe-5ee75aa2a3ec',
    'relationship_name' => 'account_aos_invoices',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Invoices',
    'rhs_table' => 'aos_invoices',
    'rhs_key' => 'billing_account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_aos_contracts' => 
  array (
    'id' => '88df7dc8-38db-f93b-cc49-5ee75a595e41',
    'relationship_name' => 'account_aos_contracts',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Contracts',
    'rhs_table' => 'aos_contracts',
    'rhs_key' => 'contract_account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'emails_accounts_rel' => 
  array (
    'id' => '92dd0516-8d11-25a7-45d4-5ee75a7d4d08',
    'relationship_name' => 'emails_accounts_rel',
    'lhs_module' => 'Emails',
    'lhs_table' => 'emails',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'emails_beans',
    'join_key_lhs' => 'email_id',
    'join_key_rhs' => 'bean_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'bean_module',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForEmails',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'jjwg_Maps_accounts' => 
  array (
    'id' => 'c92b0492-ef0b-b8fc-c01f-5ee75aefe181',
    'relationship_name' => 'jjwg_Maps_accounts',
    'lhs_module' => 'jjwg_Maps',
    'lhs_table' => 'jjwg_Maps',
    'lhs_key' => 'parent_id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_bugs' => 
  array (
    'id' => '36f52b46-7b0a-78da-0cec-5ee75a1abf93',
    'relationship_name' => 'accounts_bugs',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Bugs',
    'rhs_table' => 'bugs',
    'rhs_key' => 'id',
    'join_table' => 'accounts_bugs',
    'join_key_lhs' => 'account_id',
    'join_key_rhs' => 'bug_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => 'default',
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_contacts' => 
  array (
    'id' => '37113429-9933-d894-ee7b-5ee75af30268',
    'relationship_name' => 'accounts_contacts',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Contacts',
    'rhs_table' => 'contacts',
    'rhs_key' => 'id',
    'join_table' => 'accounts_contacts',
    'join_key_lhs' => 'account_id',
    'join_key_rhs' => 'contact_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_opportunities' => 
  array (
    'id' => '372b6fd2-6edc-5dff-7894-5ee75aab0624',
    'relationship_name' => 'accounts_opportunities',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'accounts_opportunities',
    'join_key_lhs' => 'account_id',
    'join_key_rhs' => 'opportunity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'prospect_list_accounts' => 
  array (
    'id' => '393aa307-e971-f5bd-8e21-5ee75ad28bbd',
    'relationship_name' => 'prospect_list_accounts',
    'lhs_module' => 'ProspectLists',
    'lhs_table' => 'prospect_lists',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'prospect_lists_prospects',
    'join_key_lhs' => 'prospect_list_id',
    'join_key_rhs' => 'related_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'related_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForProspectLists',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'projects_accounts' => 
  array (
    'id' => '399c28ee-a6db-eea9-5f0d-5ee75a54b5cd',
    'relationship_name' => 'projects_accounts',
    'lhs_module' => 'Project',
    'lhs_table' => 'project',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'projects_accounts',
    'join_key_lhs' => 'project_id',
    'join_key_rhs' => 'account_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'documents_accounts' => 
  array (
    'id' => '3a5a11d7-25f4-4e1a-33ae-5ee75ad17a93',
    'relationship_name' => 'documents_accounts',
    'lhs_module' => 'Documents',
    'lhs_table' => 'documents',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'documents_accounts',
    'join_key_lhs' => 'document_id',
    'join_key_rhs' => 'account_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_ptg_sql_server_1' => 
  array (
    'id' => '3e32e2d5-fac4-6527-edb1-5ee75ada59e0',
    'relationship_name' => 'accounts_ptg_sql_server_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_SQL_Server',
    'rhs_table' => 'ptg_sql_server',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_sql_server_1_c',
    'join_key_lhs' => 'accounts_ptg_sql_server_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_sql_server_1ptg_sql_server_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_isp_information_1' => 
  array (
    'id' => '3e7d6eeb-4730-1c70-f552-5ee75a90dbfa',
    'relationship_name' => 'accounts_ptg_isp_information_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_ISP_Information',
    'rhs_table' => 'ptg_isp_information',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_isp_information_1_c',
    'join_key_lhs' => 'accounts_ptg_isp_information_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_isp_information_1ptg_isp_information_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_resources_1' => 
  array (
    'id' => '3e9553bc-95dc-279a-7145-5ee75a3f9e73',
    'relationship_name' => 'accounts_ptg_resources_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Resources',
    'rhs_table' => 'ptg_resources',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_resources_1_c',
    'join_key_lhs' => 'accounts_ptg_resources_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_resources_1ptg_resources_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_quickbooks_1' => 
  array (
    'id' => '3ec886b8-a3bd-d5b8-2545-5ee75af043ce',
    'relationship_name' => 'accounts_ptg_quickbooks_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_QuickBooks',
    'rhs_table' => 'ptg_quickbooks',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_quickbooks_1_c',
    'join_key_lhs' => 'accounts_ptg_quickbooks_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_quickbooks_1ptg_quickbooks_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_hostedantisoftwareemail_1' => 
  array (
    'id' => '3efa6aab-a611-b94c-fe22-5ee75a70615c',
    'relationship_name' => 'accounts_ptg_hostedantisoftwareemail_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_HostedAntiSoftwareEmail',
    'rhs_table' => 'ptg_hostedantisoftwareemail',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_hostedantisoftwareemail_1_c',
    'join_key_lhs' => 'accounts_ptg_hostedantisoftwareemail_1accounts_ida',
    'join_key_rhs' => 'accounts_p4debreemail_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_activedirectory_1' => 
  array (
    'id' => '3f327b3d-dcb2-a796-b82a-5ee75a452f33',
    'relationship_name' => 'accounts_ptg_activedirectory_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_ActiveDirectory',
    'rhs_table' => 'ptg_activedirectory',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_activedirectory_1_c',
    'join_key_lhs' => 'accounts_ptg_activedirectory_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_activedirectory_1ptg_activedirectory_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_otherlicensedsoftwaredesktop_1' => 
  array (
    'id' => '3f52bde9-7148-405f-f08f-5ee75a8c79ff',
    'relationship_name' => 'accounts_ptg_otherlicensedsoftwaredesktop_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_OtherLicensedSoftwareDesktop',
    'rhs_table' => 'ptg_otherlicensedsoftwaredesktop',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_otherlicensedsoftwaredesktop_1_c',
    'join_key_lhs' => 'accounts_ptg_otherlicensedsoftwaredesktop_1accounts_ida',
    'join_key_rhs' => 'accounts_p72a7desktop_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_quickbooksdesktop_1' => 
  array (
    'id' => '3fb376a4-f7e8-22dc-eb5f-5ee75a289cd0',
    'relationship_name' => 'accounts_ptg_quickbooksdesktop_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_QuickBooksDesktop',
    'rhs_table' => 'ptg_quickbooksdesktop',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_quickbooksdesktop_1_c',
    'join_key_lhs' => 'accounts_ptg_quickbooksdesktop_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_quickbooksdesktop_1ptg_quickbooksdesktop_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_routerinformation_1' => 
  array (
    'id' => '4016105a-b5c0-15e4-de23-5ee75a5a38a3',
    'relationship_name' => 'accounts_ptg_routerinformation_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_RouterInformation',
    'rhs_table' => 'ptg_routerinformation',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_routerinformation_1_c',
    'join_key_lhs' => 'accounts_ptg_routerinformation_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_routerinformation_1ptg_routerinformation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_antivirus_server_information_1' => 
  array (
    'id' => '40833b02-9b76-d32e-8f68-5ee75ad1669b',
    'relationship_name' => 'accounts_ptg_antivirus_server_information_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Antivirus_Server_Information',
    'rhs_table' => 'ptg_antivirus_server_information',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_antivirus_server_information_1_c',
    'join_key_lhs' => 'accounts_ptg_antivirus_server_information_1accounts_ida',
    'join_key_rhs' => 'accounts_p52e7rmation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_localareanetworkinformation_1' => 
  array (
    'id' => '40b32e47-2dc9-2227-354e-5ee75ac91abb',
    'relationship_name' => 'accounts_ptg_localareanetworkinformation_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_LocalAreaNetworkInformation',
    'rhs_table' => 'ptg_localareanetworkinformation',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_localareanetworkinformation_1_c',
    'join_key_lhs' => 'accounts_ptg_localareanetworkinformation_1accounts_ida',
    'join_key_rhs' => 'accounts_p00c7rmation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_hosted_email_services_1' => 
  array (
    'id' => '412c02be-d40d-60e7-25a5-5ee75a01addc',
    'relationship_name' => 'accounts_ptg_hosted_email_services_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Hosted_Email_Services',
    'rhs_table' => 'ptg_hosted_email_services',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_hosted_email_services_1_c',
    'join_key_lhs' => 'accounts_ptg_hosted_email_services_1accounts_ida',
    'join_key_rhs' => 'accounts_pf800ervices_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_local_admin_credentials_1' => 
  array (
    'id' => '41435d0f-4340-f30b-c48a-5ee75aef7297',
    'relationship_name' => 'accounts_ptg_local_admin_credentials_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Local_Admin_Credentials',
    'rhs_table' => 'ptg_local_admin_credentials',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_local_admin_credentials_1_c',
    'join_key_lhs' => 'accounts_ptg_local_admin_credentials_1accounts_ida',
    'join_key_rhs' => 'accounts_p6cc2entials_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_firewall_1' => 
  array (
    'id' => '417472e3-5af1-0a8e-25b1-5ee75a8e6699',
    'relationship_name' => 'accounts_ptg_firewall_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Firewall',
    'rhs_table' => 'ptg_firewall',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_firewall_1_c',
    'join_key_lhs' => 'accounts_ptg_firewall_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_firewall_1ptg_firewall_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_hosting_and_registrar_1' => 
  array (
    'id' => '41d42534-c6eb-d202-3c01-5ee75afecc11',
    'relationship_name' => 'accounts_ptg_hosting_and_registrar_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Hosting_And_Registrar',
    'rhs_table' => 'ptg_hosting_and_registrar',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_hosting_and_registrar_1_c',
    'join_key_lhs' => 'accounts_ptg_hosting_and_registrar_1accounts_ida',
    'join_key_rhs' => 'accounts_p9380gistrar_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_otherlicensedsoftware_1' => 
  array (
    'id' => '41ecbead-7a0f-c441-3f7e-5ee75aff674f',
    'relationship_name' => 'accounts_ptg_otherlicensedsoftware_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_OtherLicensedSoftware',
    'rhs_table' => 'ptg_otherlicensedsoftware',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_otherlicensedsoftware_1_c',
    'join_key_lhs' => 'accounts_ptg_otherlicensedsoftware_1accounts_ida',
    'join_key_rhs' => 'accounts_pbb15oftware_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_otherunlicensedsoftware_1' => 
  array (
    'id' => '4204968c-ab0f-acf5-3564-5ee75a2e25bf',
    'relationship_name' => 'accounts_ptg_otherunlicensedsoftware_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_OtherUnlicensedSoftware',
    'rhs_table' => 'ptg_otherunlicensedsoftware',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_otherunlicensedsoftware_1_c',
    'join_key_lhs' => 'accounts_ptg_otherunlicensedsoftware_1accounts_ida',
    'join_key_rhs' => 'accounts_p3851oftware_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_wirelessinformation_1' => 
  array (
    'id' => '421c5259-bdad-a91a-1f03-5ee75aa53d7c',
    'relationship_name' => 'accounts_ptg_wirelessinformation_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_WirelessInformation',
    'rhs_table' => 'ptg_wirelessinformation',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_wirelessinformation_1_c',
    'join_key_lhs' => 'accounts_ptg_wirelessinformation_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_wirelessinformation_1ptg_wirelessinformation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_microsoftoffice_1' => 
  array (
    'id' => '4234d895-236a-fc4d-029d-5ee75a0a67fa',
    'relationship_name' => 'accounts_ptg_microsoftoffice_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_MicrosoftOffice',
    'rhs_table' => 'ptg_microsoftoffice',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_microsoftoffice_1_c',
    'join_key_lhs' => 'accounts_ptg_microsoftoffice_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_microsoftoffice_1ptg_microsoftoffice_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_microsoftofficedesktop_1' => 
  array (
    'id' => '42663b5d-beca-95f2-b8c1-5ee75ad0f147',
    'relationship_name' => 'accounts_ptg_microsoftofficedesktop_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_MicrosoftOfficeDesktop',
    'rhs_table' => 'ptg_microsoftofficedesktop',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_microsoftofficedesktop_1_c',
    'join_key_lhs' => 'accounts_ptg_microsoftofficedesktop_1accounts_ida',
    'join_key_rhs' => 'accounts_pe92adesktop_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_onpremise_email_services_1' => 
  array (
    'id' => '42c84b30-e4c0-f95c-c82b-5ee75adbd542',
    'relationship_name' => 'accounts_ptg_onpremise_email_services_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_OnPremise_Email_Services',
    'rhs_table' => 'ptg_onpremise_email_services',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_onpremise_email_services_1_c',
    'join_key_lhs' => 'accounts_ptg_onpremise_email_services_1accounts_ida',
    'join_key_rhs' => 'accounts_p0fd7ervices_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_switches_1' => 
  array (
    'id' => '42dfe3d5-49d5-5847-6e0f-5ee75a07a766',
    'relationship_name' => 'accounts_ptg_switches_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Switches',
    'rhs_table' => 'ptg_switches',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_switches_1_c',
    'join_key_lhs' => 'accounts_ptg_switches_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_switches_1ptg_switches_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_webserverintranet_1' => 
  array (
    'id' => '42f604d8-649b-5f64-d762-5ee75a7c5300',
    'relationship_name' => 'accounts_ptg_webserverintranet_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_WebServerIntranet',
    'rhs_table' => 'ptg_webserverintranet',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_webserverintranet_1_c',
    'join_key_lhs' => 'accounts_ptg_webserverintranet_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_webserverintranet_1ptg_webserverintranet_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_network_drives_1' => 
  array (
    'id' => '4323a3db-a654-c8d4-3bb5-5ee75ab9eaa3',
    'relationship_name' => 'accounts_ptg_network_drives_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Network_Drives',
    'rhs_table' => 'ptg_network_drives',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_network_drives_1_c',
    'join_key_lhs' => 'accounts_ptg_network_drives_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_network_drives_1ptg_network_drives_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_backup_software_1' => 
  array (
    'id' => '4339c97b-8215-3ead-da86-5ee75afc1020',
    'relationship_name' => 'accounts_ptg_backup_software_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Backup_Software',
    'rhs_table' => 'ptg_backup_software',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_backup_software_1_c',
    'join_key_lhs' => 'accounts_ptg_backup_software_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_backup_software_1ptg_backup_software_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_sharepoint_1' => 
  array (
    'id' => '435080c8-5e93-5c10-4bc6-5ee75a2c2ac5',
    'relationship_name' => 'accounts_ptg_sharepoint_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_SharePoint',
    'rhs_table' => 'ptg_sharepoint',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_sharepoint_1_c',
    'join_key_lhs' => 'accounts_ptg_sharepoint_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_sharepoint_1ptg_sharepoint_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_citrixservers_1' => 
  array (
    'id' => '43c3c7a4-a08f-ad70-3d34-5ee75ab42c1e',
    'relationship_name' => 'accounts_ptg_citrixservers_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_CitrixServers',
    'rhs_table' => 'ptg_citrixservers',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_citrixservers_1_c',
    'join_key_lhs' => 'accounts_ptg_citrixservers_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_citrixservers_1ptg_citrixservers_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_client_connectivity_1' => 
  array (
    'id' => '43da7f26-150f-1c9a-1fdc-5ee75a8dddb7',
    'relationship_name' => 'accounts_ptg_client_connectivity_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Client_Connectivity',
    'rhs_table' => 'ptg_client_connectivity',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_client_connectivity_1_c',
    'join_key_lhs' => 'accounts_ptg_client_connectivity_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_client_connectivity_1ptg_client_connectivity_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_printers_1' => 
  array (
    'id' => '43f0afb0-8155-634b-4e1f-5ee75ac2cc5c',
    'relationship_name' => 'accounts_ptg_printers_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Printers',
    'rhs_table' => 'ptg_printers',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_printers_1_c',
    'join_key_lhs' => 'accounts_ptg_printers_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_printers_1ptg_printers_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_odbc_1' => 
  array (
    'id' => '44079223-93e9-755e-12ee-5ee75adb8be1',
    'relationship_name' => 'accounts_ptg_odbc_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_ODBC',
    'rhs_table' => 'ptg_odbc',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_odbc_1_c',
    'join_key_lhs' => 'accounts_ptg_odbc_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_odbc_1ptg_odbc_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_thirdpartycontactinformation_1' => 
  array (
    'id' => '441e565d-9c47-dd09-bce0-5ee75ae610bb',
    'relationship_name' => 'accounts_ptg_thirdpartycontactinformation_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_ThirdPartyContactInformation',
    'rhs_table' => 'ptg_thirdpartycontactinformation',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_thirdpartycontactinformation_1_c',
    'join_key_lhs' => 'accounts_ptg_thirdpartycontactinformation_1accounts_ida',
    'join_key_rhs' => 'accounts_p1ff0rmation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_remoteaccessinformation_1' => 
  array (
    'id' => '44674f99-cc2c-3383-cee7-5ee75a354ef1',
    'relationship_name' => 'accounts_ptg_remoteaccessinformation_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_RemoteAccessInformation',
    'rhs_table' => 'ptg_remoteaccessinformation',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_remoteaccessinformation_1_c',
    'join_key_lhs' => 'accounts_ptg_remoteaccessinformation_1accounts_ida',
    'join_key_rhs' => 'accounts_p197frmation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_sharepointonpremise_1' => 
  array (
    'id' => '447ebca2-088a-6f41-30e3-5ee75a8bac7f',
    'relationship_name' => 'accounts_ptg_sharepointonpremise_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_SharepointOnPremise',
    'rhs_table' => 'ptg_sharepointonpremise',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_sharepointonpremise_1_c',
    'join_key_lhs' => 'accounts_ptg_sharepointonpremise_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_sharepointonpremise_1ptg_sharepointonpremise_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_camera_system_1' => 
  array (
    'rhs_label' => 'Camera System',
    'lhs_label' => 'Customers',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Accounts',
    'rhs_module' => 'ptg_Camera_System',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'accounts_ptg_camera_system_1',
  ),
);