<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'campaign_accounts' => 
  array (
    'id' => 'bea8b35f-8616-92dc-9635-5ede7741cd79',
    'relationship_name' => 'campaign_accounts',
    'lhs_module' => 'Campaigns',
    'lhs_table' => 'campaigns',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'campaign_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_modified_user' => 
  array (
    'id' => 'c5d7104f-d792-dde2-92cb-5ede776e0ab2',
    'relationship_name' => 'accounts_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_created_by' => 
  array (
    'id' => 'c5e94be2-3ba4-fb1a-35c0-5ede77abd697',
    'relationship_name' => 'accounts_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_assigned_user' => 
  array (
    'id' => 'c5fa65d5-b762-783f-8100-5ede7737ee0d',
    'relationship_name' => 'accounts_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_accounts' => 
  array (
    'id' => 'c60da885-a6e2-0443-03fc-5ede7725f319',
    'relationship_name' => 'securitygroups_accounts',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'member_accounts' => 
  array (
    'id' => 'c6455adf-2a28-023b-4e83-5ede77b9246d',
    'relationship_name' => 'member_accounts',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_cases' => 
  array (
    'id' => 'c658b2d5-8b99-90f7-c360-5ede77bb4a12',
    'relationship_name' => 'account_cases',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Cases',
    'rhs_table' => 'cases',
    'rhs_key' => 'account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_tasks' => 
  array (
    'id' => 'c6695f69-c2a2-8449-8d62-5ede77b13c95',
    'relationship_name' => 'account_tasks',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_notes' => 
  array (
    'id' => 'c67a310e-f2b7-d597-adbf-5ede7724e3b8',
    'relationship_name' => 'account_notes',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_meetings' => 
  array (
    'id' => 'c68cd878-7ffd-c499-de0d-5ede7727824f',
    'relationship_name' => 'account_meetings',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_calls' => 
  array (
    'id' => 'c69fb7e1-c18d-7630-f352-5ede774285b7',
    'relationship_name' => 'account_calls',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_emails' => 
  array (
    'id' => 'c6b11f37-738f-2dd8-b19b-5ede770cc5c7',
    'relationship_name' => 'account_emails',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'emails',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => 'ForEmails',
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_leads' => 
  array (
    'id' => 'c6c35b87-ba05-9779-2d1d-5ede777fb6b5',
    'relationship_name' => 'account_leads',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Leads',
    'rhs_table' => 'leads',
    'rhs_key' => 'account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_aos_quotes' => 
  array (
    'id' => 'c6e5d650-019c-9f49-2578-5ede77f5ed45',
    'relationship_name' => 'account_aos_quotes',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Quotes',
    'rhs_table' => 'aos_quotes',
    'rhs_key' => 'billing_account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_aos_invoices' => 
  array (
    'id' => 'c6f66def-3c29-ad1d-6cc2-5ede77974232',
    'relationship_name' => 'account_aos_invoices',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Invoices',
    'rhs_table' => 'aos_invoices',
    'rhs_key' => 'billing_account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'account_aos_contracts' => 
  array (
    'id' => 'c7085d85-13c9-fafc-354b-5ede77daed5f',
    'relationship_name' => 'account_aos_contracts',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Contracts',
    'rhs_table' => 'aos_contracts',
    'rhs_key' => 'contract_account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'emails_accounts_rel' => 
  array (
    'id' => 'cd2b83c7-5c57-636b-4009-5ede774b8576',
    'relationship_name' => 'emails_accounts_rel',
    'lhs_module' => 'Emails',
    'lhs_table' => 'emails',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'emails_beans',
    'join_key_lhs' => 'email_id',
    'join_key_rhs' => 'bean_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'bean_module',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForEmails',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'jjwg_Maps_accounts' => 
  array (
    'id' => 'eb67fd11-9e37-359a-6ba4-5ede77cd7ec7',
    'relationship_name' => 'jjwg_Maps_accounts',
    'lhs_module' => 'jjwg_Maps',
    'lhs_table' => 'jjwg_Maps',
    'lhs_key' => 'parent_id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_bugs' => 
  array (
    'id' => '2e54641e-d0c4-8bd4-c9f5-5ede77cb65e3',
    'relationship_name' => 'accounts_bugs',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Bugs',
    'rhs_table' => 'bugs',
    'rhs_key' => 'id',
    'join_table' => 'accounts_bugs',
    'join_key_lhs' => 'account_id',
    'join_key_rhs' => 'bug_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => 'default',
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_contacts' => 
  array (
    'id' => '2e705c1a-ff50-79ee-e49a-5ede77524e75',
    'relationship_name' => 'accounts_contacts',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Contacts',
    'rhs_table' => 'contacts',
    'rhs_key' => 'id',
    'join_table' => 'accounts_contacts',
    'join_key_lhs' => 'account_id',
    'join_key_rhs' => 'contact_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_opportunities' => 
  array (
    'id' => '2e883fe6-b394-e635-6156-5ede7720d3ba',
    'relationship_name' => 'accounts_opportunities',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'accounts_opportunities',
    'join_key_lhs' => 'account_id',
    'join_key_rhs' => 'opportunity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'prospect_list_accounts' => 
  array (
    'id' => '311c2873-51d8-68e6-5b89-5ede77c9bb7b',
    'relationship_name' => 'prospect_list_accounts',
    'lhs_module' => 'ProspectLists',
    'lhs_table' => 'prospect_lists',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'prospect_lists_prospects',
    'join_key_lhs' => 'prospect_list_id',
    'join_key_rhs' => 'related_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'related_type',
    'relationship_role_column_value' => 'Accounts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForProspectLists',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'projects_accounts' => 
  array (
    'id' => '3180f16d-0ac3-b5bc-3240-5ede77bbb8d9',
    'relationship_name' => 'projects_accounts',
    'lhs_module' => 'Project',
    'lhs_table' => 'project',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'projects_accounts',
    'join_key_lhs' => 'project_id',
    'join_key_rhs' => 'account_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'documents_accounts' => 
  array (
    'id' => '322d6472-7b17-f327-43cc-5ede77276610',
    'relationship_name' => 'documents_accounts',
    'lhs_module' => 'Documents',
    'lhs_table' => 'documents',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'documents_accounts',
    'join_key_lhs' => 'document_id',
    'join_key_rhs' => 'account_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_ptg_sql_server_1' => 
  array (
    'id' => '35f53825-14b6-9620-2e35-5ede772a69fc',
    'relationship_name' => 'accounts_ptg_sql_server_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_SQL_Server',
    'rhs_table' => 'ptg_sql_server',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_sql_server_1_c',
    'join_key_lhs' => 'accounts_ptg_sql_server_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_sql_server_1ptg_sql_server_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_isp_information_1' => 
  array (
    'id' => '364bc329-951d-938e-b8e9-5ede77b125c4',
    'relationship_name' => 'accounts_ptg_isp_information_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_ISP_Information',
    'rhs_table' => 'ptg_isp_information',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_isp_information_1_c',
    'join_key_lhs' => 'accounts_ptg_isp_information_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_isp_information_1ptg_isp_information_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_resources_1' => 
  array (
    'id' => '3666cc45-6cb6-8072-a681-5ede77b6014c',
    'relationship_name' => 'accounts_ptg_resources_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Resources',
    'rhs_table' => 'ptg_resources',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_resources_1_c',
    'join_key_lhs' => 'accounts_ptg_resources_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_resources_1ptg_resources_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_quickbooks_1' => 
  array (
    'id' => '36818954-171c-2f9e-4430-5ede77a79ef0',
    'relationship_name' => 'accounts_ptg_quickbooks_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_QuickBooks',
    'rhs_table' => 'ptg_quickbooks',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_quickbooks_1_c',
    'join_key_lhs' => 'accounts_ptg_quickbooks_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_quickbooks_1ptg_quickbooks_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_activedirectory_1' => 
  array (
    'id' => '36b7b42c-5a49-cc21-be04-5ede77535a12',
    'relationship_name' => 'accounts_ptg_activedirectory_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_ActiveDirectory',
    'rhs_table' => 'ptg_activedirectory',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_activedirectory_1_c',
    'join_key_lhs' => 'accounts_ptg_activedirectory_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_activedirectory_1ptg_activedirectory_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_otherlicensedsoftwaredesktop_1' => 
  array (
    'id' => '36d1f3c5-b5e1-50ba-ffdc-5ede7723ec5c',
    'relationship_name' => 'accounts_ptg_otherlicensedsoftwaredesktop_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_OtherLicensedSoftwareDesktop',
    'rhs_table' => 'ptg_otherlicensedsoftwaredesktop',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_otherlicensedsoftwaredesktop_1_c',
    'join_key_lhs' => 'accounts_ptg_otherlicensedsoftwaredesktop_1accounts_ida',
    'join_key_rhs' => 'accounts_p72a7desktop_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_quickbooksdesktop_1' => 
  array (
    'id' => '372170e9-ab5c-f88e-2f80-5ede77044fd4',
    'relationship_name' => 'accounts_ptg_quickbooksdesktop_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_QuickBooksDesktop',
    'rhs_table' => 'ptg_quickbooksdesktop',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_quickbooksdesktop_1_c',
    'join_key_lhs' => 'accounts_ptg_quickbooksdesktop_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_quickbooksdesktop_1ptg_quickbooksdesktop_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_routerinformation_1' => 
  array (
    'id' => '37757895-876c-0cf4-ff7c-5ede772685ae',
    'relationship_name' => 'accounts_ptg_routerinformation_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_RouterInformation',
    'rhs_table' => 'ptg_routerinformation',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_routerinformation_1_c',
    'join_key_lhs' => 'accounts_ptg_routerinformation_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_routerinformation_1ptg_routerinformation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_antivirus_server_information_1' => 
  array (
    'id' => '37c8a9ea-83b8-a15d-f97a-5ede777bde08',
    'relationship_name' => 'accounts_ptg_antivirus_server_information_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Antivirus_Server_Information',
    'rhs_table' => 'ptg_antivirus_server_information',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_antivirus_server_information_1_c',
    'join_key_lhs' => 'accounts_ptg_antivirus_server_information_1accounts_ida',
    'join_key_rhs' => 'accounts_p52e7rmation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_localareanetworkinformation_1' => 
  array (
    'id' => '37febf87-ccab-de8c-bbea-5ede775d83d8',
    'relationship_name' => 'accounts_ptg_localareanetworkinformation_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_LocalAreaNetworkInformation',
    'rhs_table' => 'ptg_localareanetworkinformation',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_localareanetworkinformation_1_c',
    'join_key_lhs' => 'accounts_ptg_localareanetworkinformation_1accounts_ida',
    'join_key_rhs' => 'accounts_p00c7rmation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_hosted_email_services_1' => 
  array (
    'id' => '3862d867-2ad8-09b6-ab9e-5ede773affe6',
    'relationship_name' => 'accounts_ptg_hosted_email_services_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Hosted_Email_Services',
    'rhs_table' => 'ptg_hosted_email_services',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_hosted_email_services_1_c',
    'join_key_lhs' => 'accounts_ptg_hosted_email_services_1accounts_ida',
    'join_key_rhs' => 'accounts_pf800ervices_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_local_admin_credentials_1' => 
  array (
    'id' => '387cd690-f9cf-fa56-8cb2-5ede7735a7c6',
    'relationship_name' => 'accounts_ptg_local_admin_credentials_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Local_Admin_Credentials',
    'rhs_table' => 'ptg_local_admin_credentials',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_local_admin_credentials_1_c',
    'join_key_lhs' => 'accounts_ptg_local_admin_credentials_1accounts_ida',
    'join_key_rhs' => 'accounts_p6cc2entials_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_firewall_1' => 
  array (
    'id' => '38ada507-049c-0793-5bb0-5ede77d4d038',
    'relationship_name' => 'accounts_ptg_firewall_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Firewall',
    'rhs_table' => 'ptg_firewall',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_firewall_1_c',
    'join_key_lhs' => 'accounts_ptg_firewall_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_firewall_1ptg_firewall_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_hosting_and_registrar_1' => 
  array (
    'id' => '3913c1ca-a76d-51a7-ed3c-5ede7757ccb4',
    'relationship_name' => 'accounts_ptg_hosting_and_registrar_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Hosting_And_Registrar',
    'rhs_table' => 'ptg_hosting_and_registrar',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_hosting_and_registrar_1_c',
    'join_key_lhs' => 'accounts_ptg_hosting_and_registrar_1accounts_ida',
    'join_key_rhs' => 'accounts_p9380gistrar_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_otherlicensedsoftware_1' => 
  array (
    'id' => '392cc372-b286-9b78-74d7-5ede77ffd159',
    'relationship_name' => 'accounts_ptg_otherlicensedsoftware_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_OtherLicensedSoftware',
    'rhs_table' => 'ptg_otherlicensedsoftware',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_otherlicensedsoftware_1_c',
    'join_key_lhs' => 'accounts_ptg_otherlicensedsoftware_1accounts_ida',
    'join_key_rhs' => 'accounts_pbb15oftware_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_otherunlicensedsoftware_1' => 
  array (
    'id' => '394531c3-ff9b-f7b2-564d-5ede77aa7240',
    'relationship_name' => 'accounts_ptg_otherunlicensedsoftware_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_OtherUnlicensedSoftware',
    'rhs_table' => 'ptg_otherunlicensedsoftware',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_otherunlicensedsoftware_1_c',
    'join_key_lhs' => 'accounts_ptg_otherunlicensedsoftware_1accounts_ida',
    'join_key_rhs' => 'accounts_p3851oftware_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_wirelessinformation_1' => 
  array (
    'id' => '395e1e1a-4c14-1d52-adf7-5ede7736ed94',
    'relationship_name' => 'accounts_ptg_wirelessinformation_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_WirelessInformation',
    'rhs_table' => 'ptg_wirelessinformation',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_wirelessinformation_1_c',
    'join_key_lhs' => 'accounts_ptg_wirelessinformation_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_wirelessinformation_1ptg_wirelessinformation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_microsoftoffice_1' => 
  array (
    'id' => '3977c0ff-dcaf-0406-3de7-5ede7780f9d2',
    'relationship_name' => 'accounts_ptg_microsoftoffice_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_MicrosoftOffice',
    'rhs_table' => 'ptg_microsoftoffice',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_microsoftoffice_1_c',
    'join_key_lhs' => 'accounts_ptg_microsoftoffice_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_microsoftoffice_1ptg_microsoftoffice_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_microsoftofficedesktop_1' => 
  array (
    'id' => '39a8c85e-83a2-aebc-8204-5ede771909b2',
    'relationship_name' => 'accounts_ptg_microsoftofficedesktop_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_MicrosoftOfficeDesktop',
    'rhs_table' => 'ptg_microsoftofficedesktop',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_microsoftofficedesktop_1_c',
    'join_key_lhs' => 'accounts_ptg_microsoftofficedesktop_1accounts_ida',
    'join_key_rhs' => 'accounts_pe92adesktop_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_onpremise_email_services_1' => 
  array (
    'id' => '3a058805-49e5-f36d-6c80-5ede776ce32c',
    'relationship_name' => 'accounts_ptg_onpremise_email_services_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_OnPremise_Email_Services',
    'rhs_table' => 'ptg_onpremise_email_services',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_onpremise_email_services_1_c',
    'join_key_lhs' => 'accounts_ptg_onpremise_email_services_1accounts_ida',
    'join_key_rhs' => 'accounts_p0fd7ervices_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_switches_1' => 
  array (
    'id' => '3a232a8c-39ad-3d70-7d91-5ede77a1355b',
    'relationship_name' => 'accounts_ptg_switches_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Switches',
    'rhs_table' => 'ptg_switches',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_switches_1_c',
    'join_key_lhs' => 'accounts_ptg_switches_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_switches_1ptg_switches_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_webserverintranet_1' => 
  array (
    'id' => '3a3d4253-7083-42f1-0f0f-5ede77ad8b00',
    'relationship_name' => 'accounts_ptg_webserverintranet_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_WebServerIntranet',
    'rhs_table' => 'ptg_webserverintranet',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_webserverintranet_1_c',
    'join_key_lhs' => 'accounts_ptg_webserverintranet_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_webserverintranet_1ptg_webserverintranet_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_network_drives_1' => 
  array (
    'id' => '3a72d143-18a8-e986-d963-5ede77c3b415',
    'relationship_name' => 'accounts_ptg_network_drives_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Network_Drives',
    'rhs_table' => 'ptg_network_drives',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_network_drives_1_c',
    'join_key_lhs' => 'accounts_ptg_network_drives_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_network_drives_1ptg_network_drives_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_backup_software_1' => 
  array (
    'id' => '3a8abb0c-3e36-671d-33c1-5ede77dc2b5e',
    'relationship_name' => 'accounts_ptg_backup_software_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Backup_Software',
    'rhs_table' => 'ptg_backup_software',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_backup_software_1_c',
    'join_key_lhs' => 'accounts_ptg_backup_software_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_backup_software_1ptg_backup_software_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_sharepoint_1' => 
  array (
    'id' => '3aa36e93-7d6d-7d95-8bb6-5ede770a2267',
    'relationship_name' => 'accounts_ptg_sharepoint_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_SharePoint',
    'rhs_table' => 'ptg_sharepoint',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_sharepoint_1_c',
    'join_key_lhs' => 'accounts_ptg_sharepoint_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_sharepoint_1ptg_sharepoint_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_citrixservers_1' => 
  array (
    'id' => '3b25cabe-9392-e3f3-1411-5ede777698a0',
    'relationship_name' => 'accounts_ptg_citrixservers_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_CitrixServers',
    'rhs_table' => 'ptg_citrixservers',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_citrixservers_1_c',
    'join_key_lhs' => 'accounts_ptg_citrixservers_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_citrixservers_1ptg_citrixservers_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_client_connectivity_1' => 
  array (
    'id' => '3b3f7cd9-b87c-da6a-ee55-5ede77b522ed',
    'relationship_name' => 'accounts_ptg_client_connectivity_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Client_Connectivity',
    'rhs_table' => 'ptg_client_connectivity',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_client_connectivity_1_c',
    'join_key_lhs' => 'accounts_ptg_client_connectivity_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_client_connectivity_1ptg_client_connectivity_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_printers_1' => 
  array (
    'id' => '3b592fad-6b4c-f576-d56e-5ede77fc169d',
    'relationship_name' => 'accounts_ptg_printers_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_Printers',
    'rhs_table' => 'ptg_printers',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_printers_1_c',
    'join_key_lhs' => 'accounts_ptg_printers_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_printers_1ptg_printers_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_odbc_1' => 
  array (
    'id' => '3b7405d1-5e5e-0935-390c-5ede77348bc0',
    'relationship_name' => 'accounts_ptg_odbc_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_ODBC',
    'rhs_table' => 'ptg_odbc',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_odbc_1_c',
    'join_key_lhs' => 'accounts_ptg_odbc_1accounts_ida',
    'join_key_rhs' => 'accounts_ptg_odbc_1ptg_odbc_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_thirdpartycontactinformation_1' => 
  array (
    'id' => '3b8c8da1-28f5-b4ad-56d2-5ede7739b9d8',
    'relationship_name' => 'accounts_ptg_thirdpartycontactinformation_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_ThirdPartyContactInformation',
    'rhs_table' => 'ptg_thirdpartycontactinformation',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_thirdpartycontactinformation_1_c',
    'join_key_lhs' => 'accounts_ptg_thirdpartycontactinformation_1accounts_ida',
    'join_key_rhs' => 'accounts_p1ff0rmation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_remoteaccessinformation_1' => 
  array (
    'id' => '3bd847f4-0e16-a99f-eeca-5ede778896e7',
    'relationship_name' => 'accounts_ptg_remoteaccessinformation_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'ptg_RemoteAccessInformation',
    'rhs_table' => 'ptg_remoteaccessinformation',
    'rhs_key' => 'id',
    'join_table' => 'accounts_ptg_remoteaccessinformation_1_c',
    'join_key_lhs' => 'accounts_ptg_remoteaccessinformation_1accounts_ida',
    'join_key_rhs' => 'accounts_p197frmation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_ptg_hostedantisoftwareemail_1' => 
  array (
    'rhs_label' => 'Hosted Anti-Software (Email)',
    'lhs_label' => 'Customers',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Accounts',
    'rhs_module' => 'ptg_HostedAntiSoftwareEmail',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'accounts_ptg_hostedantisoftwareemail_1',
  ),
);